tasks:
  - init: |
      pip3 install -r docs/requirements.txt
      brew install vale
  - name: Open workspace on welcome page
    command: gp open .vscode/welcome.md

vscode:
  extensions:
    - lextudio.restructuredtext
    - trond-snekvik.simple-rst
    - errata-ai.vale-server
    - ms-python.python
    - eamodio.gitlens

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
